compatibility_date = "2022-09-20"
type = "javascript"
name = "userwidgets"
workers_dev = true
routes = []


[build]
command = "npm install && npm run build"
[build.upload]
format = "modules"
dir = "dist/"
main = "_worker.js"

[durable_objects]
bindings = [
	{ name = "userNamespace", class_name = "DurableUser" },
	{ name = "applicationNamespace", class_name = "DurableApplication" },
]

[env.production]
workers_dev = false
vars = { email = "", issuer = "userwidgets", adminSecret = "Rowi8zeechoLu3ac", hashSecret = "lNBKQ4aDjnZgx6dAh33ZkcxcB6q5agwr7m6M_mS3QI5eL-BTmcle-fGOpM4uSiHGj97nPr915cpHVEI9T3VEU6ir_Az6Cg5EZZEiSvb-UUXZ86r9pPEexglFyLR2ByXcUm386FpvFGxtjKCW9Kmh2Pi04bMYZTFfbsWMSCYBFfBHMyEFi0zUpT0VfUMhCNCLqq4X_RbK-mRFmFVaBpYDGW9kBD8v8Vfq4PcLNx-IJ4lhgqUmtUMogZ3v6fmdVvmbg-avibDZf5nQwBt0gL56SAUnhpbZqisnT4Q6d-lco26-eQvV-KWLLpBQCaHRgragGSpqRnZVDfGSmO7jZ7aAk90dtxmdRXswtbSGSlUc5bPGDRgk-EySflPlDKR5cT0B-EiXhtLJ1cXiKTCfIWePSfqL0-Pk6Er_VRK8o3gD6PPxoPHpN_66XHyvijBtOlKuTOBnj6xsP5e7iI8P7MLpK4pM0enKU9BDM6cK5sJCGRu4uTYXeNkT2aXAwELCLutRkX7qm6iga8jseUThaErAIFwmAzN9mdz317sKuCM578Cj3CQpuKx9lec5elEMgxLikhg6DRBatjB3MvlbR24xmiyXGmCE6UkjZjBLDuNN4DgQQxPMO0qeYRjeVpbTgQ__nWnzufE1xqwEiZV9iY2_z3OQA0oUwsLOXFAjZnKvPYIOQ2KfdwaLdieq7AlKiIbHLDetpJKvS7eWzP8QGzyPseENKDYpN--iPF7rPvwKT87FLuCCzlhoS7zyn5wfkIhCa95tPBQGcqGQ4b4zdn3gCu4vMKB20O0zO1DtugcX_T62KrpOkiVmV3g2nzHfos-FgDWvrNwurFABTajv9CSQ4oq5ispaWYKugTSLc5JaW8dMMOKG1iiArhMofc5BOP_gzdSzlPA2NsiG8XNYDoOCi7UnGcNXcTW32MJmSAOw15TlTNjzoVgCOoIxhzmG345Ckx4chsnRnvxqn_92p2T0zegbQN7ryahhYyvEv5P9CYq9H3cWOHV5yrMTaH_4coiO", privateSecret="MIICdQIBADANBgkqhkiG9w0BAQEFAASCAl8wggJbAgEAAoGBAK+O8TbsOs26ms0JpzbqvP8xeh3iXmUZI9utyH17CxQEd67juzAqKXR13aPgdN0pHgQ4MeIV/lBMMhI+pBafUDRZSa96PLDdZQBALJw14nj4j8vJLBZqexbVBHwtyrsQAE1B4Ajp50KeYnUJMvWCwfu8FqfTvuZIKLL6BLdqXajbAgMBAAECgYAD4PyjYgTKltzkutne9MDIQqeYEXBUe4G3UNelLhrIjnC2hIGWRtgzoocLH+J1IHtxTGyNuj6sN4LDtG6bsVlsRUf1FYnJVSnoFm+1miARG/JR/BjzI3TSEP5neyXFFROJbMw0Hv0ZBg+tLgHuVygm2TQXmU1TxVoUmm7yY/vRwQJBAORMxiTWhx3uIxD5IPKVWsxbxSsfyZPG/mLdIS0Y/0xukrUel/heSQo/kgruvXh3+zVtn8KvawxGuAeP/sJ2B3UCQQDE2/aBca14LGN9BuwWdCXzBbexVJFdE0u/3E9p1+Fy10wrlW72+h81QAPu3Z2unzdyVttEhWQhY8GTENzpSDUPAkBAHF84URY4jXtDdPKPrOmGoe7IoXCWEze0w6xhYbev2w1P13uNv8x7GEcG0uxaPDdLVbGblm9VTza2yPUd3s9RAkBO5cGkG4VktpWhFFcmoKJdBhubDMO9w/AGEywYxZbryfITPa7deV1soB1zbIq348P7JWh3y+ZXo31/jbCcJn5tAkA79CTUfKN7dheYVPKOv5xeykN0XKRjN7ZMiJTyURABtGjdnv2nX0po9UGVQ8xyJ63EUY3t70Nj/Gjw/g3XK8VV" }

[env.wrangler]
workers_dev = true
port = 8788
vars = { hashSecret = "hashing", adminSecret = "secret", issuer = "local" }

[env.miniflare]
workers_dev = true
vars = { hashSecret = "hashing", adminSecret = "secret", issuer = "local" }

[miniflare]
durable_objects_persist = "./.miniflare/durable-objects/"
kv_persist = "./.miniflare/kv/"
port = 8788

[[migrations]]
tag = "0.0.1"
new_classes = ["DurableApplication", "DurableUser"]
