compatibility_date = "2023-04-13"
type = "javascript"
name = "userwidgets"
workers_dev = true
routes = []
vars = { }
durable_objects.bindings = [
	{ name = "userNamespace", class_name = "DurableUser" },
	{ name = "applicationNamespace", class_name = "DurableApplication" },
]

[build]
command = "npm install && npm run build"
[build.upload]
format = "modules"
dir = "dist/"
main = "_worker.js"

[env.production]
workers_dev = false
vars = { email = "no-reply@userwidgets.com", issuer = "userwidgets" }
durable_objects.bindings = [
	{ name = "userNamespace", class_name = "DurableUser" },
	{ name = "applicationNamespace", class_name = "DurableApplication" },
]

[env.preview]
workers_dev = false
vars = { email = "no-reply@userwidgets.com", issuer = "userwidgets" }
durable_objects.bindings = [
	{ name = "userNamespace", class_name = "DurableUser" },
	{ name = "applicationNamespace", class_name = "DurableApplication" },
]

[env.miniflare]
workers_dev = true
vars = { hashSecret = "hashing", adminSecret = "userwidgetsSecret", issuer = "local" }
durable_objects.bindings = [
	{ name = "userNamespace", class_name = "DurableUser" },
	{ name = "applicationNamespace", class_name = "DurableApplication" },
]

[miniflare]
durable_objects_persist = "./.miniflare/durable-objects/"
kv_persist = "./.miniflare/kv/"
port = 8788
durable_objects.bindings = [
	{ name = "userNamespace", class_name = "DurableUser" },
	{ name = "applicationNamespace", class_name = "DurableApplication" },
]

[[migrations]]
tag = "0.0.1"
new_classes = ["DurableApplication", "DurableUser"]

# [[migrations]]
# tag="clean"
# deleted_classes = ["DurableApplication", "DurableUser"]
