compatibility_date = "2023-04-13"
type = "javascript"
name = "userwidgets"
workers_dev = true
routes = []
vars = { }
kv_namespaces = [
	{ binding = "userwidgetsStore", id = "a8172eb552734be293601fea4b34bcb9" }
]
durable_objects.bindings = [
	{ name = "userNamespace", class_name = "DurableUser" },
	{ name = "applicationNamespace", class_name = "DurableApplication" },
]

[build]
command = "npm install && npm run build"
[build.upload]
format = "modules"
dir = "dist/"
main = "_worker.js"

[env.production]
workers_dev = false
kv_namespaces = [
	{ binding = "userwidgetsStore", id = "a8172eb552734be293601fea4b34bcb9" }
]
durable_objects.bindings = [
	{ name = "userNamespace", class_name = "DurableUser" },
	{ name = "applicationNamespace", class_name = "DurableApplication" },
]
[env.production.vars]
publicKey = "MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAv288G3gLlnyt0EN5pGBcG04Dr6cUWhz6f444Q4uxAGBiBOo+vNW9oq6r5eFV4moYL66jeujAvY9yx7ZJClKnj6UilMAkvFgQ7KgvDcwATZ8zMTa9R2WQD36h1/C6tGfpU8IX31qCOHwml+BKYp5hd7MGKrH6ChWohcyPAfW6oeWd+cEfsqbgJLssW0sWXZUD1wtwtsaNySQ/aftrKiYZ6duIV/qqNeC6jbRJFhRu8XLYRzBSrYGHm+DA/oNBNXYzsVzBWL5fGae6Lz0qghF0+d8Ha/3t/4cI+r5z7VKeVIHatWXqel693agQcsi0SYo/dfO0LsIim6eXwBc5zKQwu5VI4pAG04UF8+hr6C81dKjfFDnAv4Ld5nQwMRRWJusqgecoPqH1DKnqPUeeb87gLAkcTwZG2sAYJhsuXyIeW9lXlTldc1N3N82cKhvCddEQlOKnHDRfDiFokrWvhWoJeyDaNvumAn73WYHcoBzXoGaEMXw1h4DBatW9opAKjyx5wu4R6KZi8105F2cohE3kilpXjdLSaX1/HIhjBa73D2vjDETwWKno85+lZPfrf3O9LUFqVBdCOM7QwM0ZJvYOHPzNmKodR5mH0lg8ft1LRyr99gLHtBtA0IqIhMkWuO4avqSTgYrqgagZuFseUN+uM/ESQpOH/So3G1HLA3iw5ksCAwEAAQ=="
email = "no-reply@userwidgets.com"
issuer = "userwidgets"

[env.preview]
workers_dev = false
durable_objects.bindings = [
	{ name = "userNamespace", class_name = "DurableUser" },
	{ name = "applicationNamespace", class_name = "DurableApplication" },
]
[env.preview.vars]
email = "no-reply@userwidgets.com"
issuer = "userwidgets-preview"

[env.miniflare]
workers_dev = true
kv_namespaces = [
	{ binding = "userwidgetsStore" }
]
durable_objects.bindings = [
	{ name = "userNamespace", class_name = "DurableUser" },
	{ name = "applicationNamespace", class_name = "DurableApplication" },
]
[env.miniflare.vars]
hashSecret = "randomHashPepper"
issuer = "miniflare"
adminSecret = "userwidgetsSecret"
publicKey = "MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAtEHMQ+myaJa+0MvItYX936J78rgykGpMaf7qeQ+UENauyjzAJIPGyjMMim/t1cdnhf4a4i8v4EaQMyQXcOheIyZDs6ps7s5HDqvq9WrPVevP6N8QiFT1n5WKyMakzVtDSh6wva9PTihFoRQcZEvaio9fUXNLT0qxiB6bmwXMA+oGuVWCymqLcOY3ZLbKBYt1symO9YSpTR1jaUiGtzWtaYZ2QrWZ25LimhVkgv1ewgtMx9ybH/MiRvL29u8tttvVdFoAgABP+LHJrUQG0ykWopgNQHoWNUusqplSinHJy1avgG/xH2g8wiGR8byBsnEITq6qk3ShTV/pZfHo2ckvQzYaL17/sU4+G1lscJNoB0nQkwgTopCWbBHjxV9xNyM3CbQbdo113QcqXKlNWxeUUEVttIat+zZhcr43JZPvTfHxzLLVnsT7d9FTgsJpiolOirCJ4uW4YUKmngTNWV1dkjhe5cFAX346YcwdO0oDUcWdiGg1zD739HDsMZy9s8CPcRWHZlYntVfELqoILlaO3GEaGaY3dEV2TgWOwYwIWgTTfXWC+LO+ybxafb/DyHKmPZMhox2mITuodigNtRrfhLk2xVYQjeBpQd++nbChj2GLeGCOaLAqq2ZpVOEMgG9jHpUiGeqhk81D4YCRJvy0ubRVg/oqrfUTQtnFiURQy4UCAwEAAQ=="
privateKey = "MIIJQwIBADANBgkqhkiG9w0BAQEFAASCCS0wggkpAgEAAoICAQC0QcxD6bJolr7Qy8i1hf3fonvyuDKQakxp/up5D5QQ1q7KPMAkg8bKMwyKb+3Vx2eF/hriLy/gRpAzJBdw6F4jJkOzqmzuzkcOq+r1as9V68/o3xCIVPWflYrIxqTNW0NKHrC9r09OKEWhFBxkS9qKj19Rc0tPSrGIHpubBcwD6ga5VYLKaotw5jdktsoFi3WzKY71hKlNHWNpSIa3Na1phnZCtZnbkuKaFWSC/V7CC0zH3Jsf8yJG8vb27y2229V0WgCAAE/4scmtRAbTKRaimA1AehY1S6yqmVKKccnLVq+Ab/EfaDzCIZHxvIGycQhOrqqTdKFNX+ll8ejZyS9DNhovXv+xTj4bWWxwk2gHSdCTCBOikJZsEePFX3E3IzcJtBt2jXXdBypcqU1bF5RQRW20hq37NmFyvjclk+9N8fHMstWexPt30VOCwmmKiU6KsIni5bhhQqaeBM1ZXV2SOF7lwUBffjphzB07SgNRxZ2IaDXMPvf0cOwxnL2zwI9xFYdmVie1V8QuqgguVo7cYRoZpjd0RXZOBY7BjAhaBNN9dYL4s77JvFp9v8PIcqY9kyGjHaYhO6h2KA21Gt+EuTbFVhCN4GlB376dsKGPYYt4YI5osCqrZmlU4QyAb2MelSIZ6qGTzUPhgJEm/LS5tFWD+iqt9RNC2cWJRFDLhQIDAQABAoICAEyoetUa6rud+DJVp9rCzA+ySyITAbX27t5ZAaBQZriuhBEPuusMe5r8EMZDCZNTxQvv38D3LlYjzCljnPBwcbBjEoGy5ba9VOzBYh/St7Ajo/y1+JLyBq9Cao4uJGINANXhrWpNxt1HNS1mnxhsRdmNVY0PCiUDb/Kiiaxoz7WObiOdYQzyOLDfxwj2z32CLKDv+JMjQti/ucpJhLkfg8sP2vVNw8vkcKf0lxU56XV+Vr3cbMAupxIjO7IST4+nd+SObg4BlAEAovMjrf9ZRv4IygH0qcMqlpjKsZadA6ONDwABGzsvGj+5BRcYAtQ/S7gigfpJrFt6gYjQUyVjcMxevi+DN3OweZst1zlXkwMitDBK188JDKZtEIR3dCH4hvn/VeBds05zZ3rKtwJwtoV38qxkQSiGuhTBA87J9eGMMWzKSW2mzVFMe06o9VHvkf2NUvcJsPe48CUzuZFbp3mojVEulO876PsKslsOyRyHlz9pV1twLSATcHIqjY5vkcYcPG/QpTQSW9u1jf1wf5VVxC8Vzmkmf2mRmMz8kcWtoAiqfDS7/tiykzVn3MPnX4UcmT/8bv/u8PmskTXIpsmbo259V5yM2x/+Y3KZMFxEAmuYQyMtfNvwAnMqcDjBJM0GZ7gxpDU850ZHxdM8jdA28vLQMBqH/VjIZ7FpiWm1AoIBAQDPPLy04lsZKD9wUO6uUwvpEsU4/EBFYKy/Gi4tcx9g+xRAXmhjLgiVX5lt4GzNpuKNtmElh4sw7+w6vlHhcqvYTfWEgopzDvnCI1Jtr4vVG4apd7AKw7Rjbq+vUNrAPQzeYTG/NyMc15RAWX4itSC4myGkhR4qJTvxENvuKPSOsrCEg0LUxfSJ3sknoTC66PvdSAelMxzuS6r6JirudeCJ88u+t/sNDz+IHJQxshcxc/oZjNQIWSMJLYg8mGPg6T8uEqtHxuyuLMHjPK2v96sbEonFjWlJ+lUwPu+87cpD1dQImHcbTfq84E6xlHkcs66bR1pXR1Cbz3IuH+MRJrcvAoIBAQDeq90uaLO0NJrgHIjSg/W7S4pX8xN6I9BDcuCvpkBHFHLTrcYhNWmFxTs5uAlcK2iR03KVCpS57TMMCDDiCEepiQLEat6aXhf+2fdcsLWuyjY2aB9lIzHDkCmZDff3XRzVSwRoHnlC3JSVHIjCj5ZPmEHtLCridKTR0gr89e9vJNTKyTAR6RADFou3RmIin7cdN6jjkJJWdEFlmoN6uc/2xB4c2b/XnBtaf7vEJlx3Ded5ohEi/viAv3ani02p8UERAWFx78gCLFzr/RL29ue8FQ5cjm1LRqJsFDrKDkcNwAdPxVfiEd6yIEDudFf0Er7MftIsffQmaF/L0YA8RLuLAoIBAQCLQe4wwtaijhgrGkd5Xxbm1RUwmNl7hV4vwKD9K5oPakkOhCIzW3CrJ6WLXz7d5uHghoi7VlzjUqX0R4XwMEVnweNU2v+8F3kfyuqOCGO3nZqc8G+cnCvwkSV/cp68hYnLOZbbPmra68aUg06udfZ59szhqA5AFes0r7aKUH0eEtdpBGd5YVhU+R9FAR0kzIDLDqcMjM9JFhHbrKA2w4FSUkA8dZc/DFsN1N6Ekn7hXWTXnHmy7msLtMwSo/ih3zr0c9kjD3pmBG95ioHQeGZDd+6akM8KxixOkkw5MbU0ZlDoQcPv1jPCjhxzWikUb23KrGT5t1NkkD7S3dyQ3upDAoIBADxb8A/Vd+kAXX8knP4boS/NEUo37O6t6JVv/XH/qeraoym4MD3uQZVuWliSB4+BgM4OuD+oZ5pirvSy/7U1s19EcYiWw5KqsOx3XzMz/3vK+pkS7ne265Vsbao8fBwElH1I4X/ryskSDADDhFrhG0imKDDHSTSrk8YAntPlQqspG7mAgdRJDfsYUHU00gM6siNsZA6TsOdYiiWllcBdv/7POK5vZC5o9Y05lMdd8rCfB0EUanrHDMuxmtNd0oafjBi0/BorelcEeYfKySpC0ZxNROBYB05hbkPH1AvThPU4OYMpJmJ0n54/WfqJdRIHRsseEZDX76e9oUIZnx43L3MCggEBAKjyxfCxGi012LHNajWQ9quaP4NeT7lZBpfyf3kZJPpNOpeCM1p0J1FPvyjc5c0mgYO2tc6BOQnkvda5ebEODnzJlYvJ6dN/LvopXKIlKzWCG+fOh+5qdCAPbm4F8OOO96knDWVQGj9j1dl6fnN52zEGF0anvqOFBsXql1yb/QhnzWmTcrdA9CXo9GijehhVoDupaCYgd101ZgkMGCkgtReid2O7Y0tWzLKVWXMccvmblwxjMNO/7QZcT31D9nP809mNgQR3YLZFXwHEhdzbOsmnour8t0Jwp2EZMdkoMrWwyRZdru0LKBqIRdpE5ckNUs61dIMXMIrrOiMcuqMFkBY="

[miniflare]
durable_objects_persist = "./.miniflare/durable-objects/"
kv_persist = "./.miniflare/kv/"
port = 8788
durable_objects.bindings = [
	{ name = "userNamespace", class_name = "DurableUser" },
	{ name = "applicationNamespace", class_name = "DurableApplication" },
]

[[migrations]]
tag = "0.0.1"
new_classes = ["DurableApplication", "DurableUser"]

# [[migrations]]
# tag="clean"
# deleted_classes = ["DurableApplication", "DurableUser"]
